### PR TITLE
Add Account Recovery Audit pt2 and Multi-owned ECDSA reports

### PR DESCRIPTION
**Pull request by filmakarov**
# Summary

Add Account Recovery Audit pt2 and Multi-owned ECDSA reports

### CODE REVIEW

**Comment by livingrockrises** [comment]
can we have title of every report suffixed as Final.

**Review by livingrockrises — COMMENTED** [review]
left one comment

**Comment by filmakarov** [comment]
removed the draft report.
Will add suffixes

**Comment by Aboudjem** [comment]
Added missing report and final report

**Review by Aboudjem — APPROVED** [review]

**Pull request merged**
