### PR TITLE
Added Test Cases per Zellic audit questions

### PR DESCRIPTION
**Pull request by filmakarov**
# Summary

- In the BatchedSessionRouterModule, added a check to ensure that the decoded sessionData array contains enough elements for all the actions and corresponding tests
- For the ERC20SessionValidationModule, added tests to ensure it reverts when userOp.callData is too short or when the length for the inner bytes array is not correct

Related Issue: [SMA-143,](https://linear.app/biconomy/issue/SMA-143/add-length-related-checks-to-erc20-svm) and [SMA-144](https://linear.app/biconomy/issue/SMA-144/test-empty-sessiondata-in-batchedsessionrouter)

## Change Type

- Unit Tests
- Bug Fix

# Checklist

- [x] My code follows this project's style guidelines
- [x] I've reviewed my own code
- [x] I've added comments for any hard-to-understand areas
- [x] I've updated the documentation if necessary
- [x] My changes generate no new warnings
- [x] I've added tests that prove my fix is effective or my feature works
- [x] All unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published

P.S. The branch name is `fix/` not `/fixes` because it was created before the discussion about naming convention. Next time will make it `fixes/`.

### CODE REVIEW

**Review by ankurdubey521 — APPROVED** [review]
LGTM, but I think you need to fix a few linting errors

**Review by Aboudjem — APPROVED** [review]

**Comment by filmakarov** [comment]
@ankurdubey521 @Aboudjem Sorry guys, it requires approvals from you again.
Next time will fix the linting first before requesting the reviews

**Comment by Aboudjem** [comment]
> @ankurdubey521 @Aboudjem Sorry guys, it requires approvals from you again. Next time will fix the linting first before requesting the reviews

No worries ! the husky hook didn't work?

**Review by Aboudjem — APPROVED** [review]

**Comment by filmakarov** [comment]
> No worries ! the husky hook didn't work?

I skipped it initially :)

**Review by ankurdubey521 — APPROVED** [review]

**Pull request merged**
